### ISSUE TITLE
Styling

### ISSUE THREAD

**Issue by Tereseus** [mmotykiewicz/tea_cozy#2]
Nice job on your styling. Your repo looks almost exactly the same as how the solution looks. I also like the way you name your classes and ids, your html looks very clean and easy to read. The buttons also take you to the right location when you click them, a lot of people forget or do not do that. The only thing I could suggest changing is the font color as your color is slightly gray and a little hard to read. 

Good job.

**Comment by mmotykiewicz** [comment]
Font color was picked based on specs (seashell).
