### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by Tereseus** [mmotykiewicz/tea_cozy#3]
Overall a good job. I found now major issues in your repository. There is a small issue with the footer that should be fixed but other than that there are no other issues. I did make a few recommendations as well with the font but that is for you to decide. Also as I stated you did a great job, almost 100% just fix that minor issue and you are all set.

Good job again.

**Comment by mmotykiewicz** [comment]
Thanks for the feedback. I'm a little behind but trying to catch up slowly!
